name: htn-cp-llm
channels:
    - conda-forge
dependencies:
    - python=3.12.0
    - scikit-learn
    - joblib
    - wheel
    - scipy<1.12.0
    - pip
    - pip:
      - graphviz
      - pandas
      - deap
      - pmlb
      - matplotlib
      - seaborn
      - df2img # save dataframes as images
      - python-dotenv
      - openai
      - statannot
      - git+https://github.com/cavalab/feat.git
      - fire
